# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from trigger_service_logger_client.models.base_response_schema import BaseResponseSchema
from trigger_service_logger_client.models.create_job_request_schema import CreateJobRequestSchema
from trigger_service_logger_client.models.failure_reason import FailureReason
from trigger_service_logger_client.models.finish_scraper_job_request_schema import FinishScraperJobRequestSchema
from trigger_service_logger_client.models.http_validation_error import HTTPValidationError
from trigger_service_logger_client.models.job_plan_log_response_schema import JobPlanLogResponseSchema
from trigger_service_logger_client.models.job_run_message import JobRunMessage
from trigger_service_logger_client.models.retry_job_request_schema import RetryJobRequestSchema
from trigger_service_logger_client.models.retry_job_response_schema import RetryJobResponseSchema
from trigger_service_logger_client.models.run_job_response_schema import RunJobResponseSchema
from trigger_service_logger_client.models.scrap_type import ScrapType
from trigger_service_logger_client.models.validation_error import ValidationError
from trigger_service_logger_client.models.validation_error_loc_inner import ValidationErrorLocInner
