# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FailureReason(str, Enum):
    """
    FailureReason
    """

    """
    allowed enum values
    """
    PROXY_ERROR = 'proxy_error'
    NOT_FOUND = 'not_found'
    SCRAP_SERVICE_OVERLOAD = 'scrap_service_overload'
    DATA_ISSUE = 'data_issue'
    PROCESS_SERVICE_OVERLOAD = 'process_service_overload'
    NO_SECTIONS='no_sections'
    NOT_ON_SALE='not_on_sale'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FailureReason from a JSON string"""
        return cls(json.loads(json_str))


