# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from trigger_service_logger_client.models.scraping_timing_stats_single_schema import ScrapingTimingStatsSingleSchema
from typing import Optional, Set
from typing_extensions import Self

class ScrapingTimingStatsSchema(BaseModel):
    """
    ScrapingTimingStatsSchema
    """ # noqa: E501
    ticketmaster: Optional[ScrapingTimingStatsSingleSchema]
    vividseats: Optional[ScrapingTimingStatsSingleSchema]
    evenue: Optional[ScrapingTimingStatsSingleSchema]
    __properties: ClassVar[List[str]] = ["ticketmaster", "vividseats", "evenue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrapingTimingStatsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ticketmaster
        if self.ticketmaster:
            _dict['ticketmaster'] = self.ticketmaster.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vividseats
        if self.vividseats:
            _dict['vividseats'] = self.vividseats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of evenue
        if self.evenue:
            _dict['evenue'] = self.evenue.to_dict()
        # set to None if ticketmaster (nullable) is None
        # and model_fields_set contains the field
        if self.ticketmaster is None and "ticketmaster" in self.model_fields_set:
            _dict['ticketmaster'] = None

        # set to None if vividseats (nullable) is None
        # and model_fields_set contains the field
        if self.vividseats is None and "vividseats" in self.model_fields_set:
            _dict['vividseats'] = None

        # set to None if evenue (nullable) is None
        # and model_fields_set contains the field
        if self.evenue is None and "evenue" in self.model_fields_set:
            _dict['evenue'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrapingTimingStatsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ticketmaster": ScrapingTimingStatsSingleSchema.from_dict(obj["ticketmaster"]) if obj.get("ticketmaster") is not None else None,
            "vividseats": ScrapingTimingStatsSingleSchema.from_dict(obj["vividseats"]) if obj.get("vividseats") is not None else None,
            "evenue": ScrapingTimingStatsSingleSchema.from_dict(obj["evenue"]) if obj.get("evenue") is not None else None
        })
        return _obj


